drainet:
  - title: 大屏
    name: components
    type: components
    groups:
      - title: bigScreen
        name: bigScreen
        items:
          - title: components
            name: components
            details:
              - title: test1
                name: test1
              - title: test2
                name: test2
              - title: test3
                name: test3
              - title: test4
                name: test4
              - title: water
                name: water
                pages:
                - title: waterStation
                  name: waterStation
                - title: waterStationBot
                  name: waterStationBot
                - title: waterStationLeft
                  name: waterStationLeft
                - title: waterStationRight
                  name: waterStationRight